version: '3'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: docker.io/postgres:14.5
    shm_size: 1g
    ports:
      - 5432:5432
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ../testdata:/testdata
      - ./pg-data/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=secret
  
  rahla:
    container_name: rahla
    hostname: rahla
    image: docker.io/datatactics/rahla:1.0.9
    ports:
      - 8181:8181
      - 8101:8101
      - 8183:8183
      - 5005:5005
    environment:
      - JAVA_MAX_MEM=2048M
      - KARAF_DEBUG=true
    volumes:
      - ./rahla/deploy:/rahla/deploy
      - ./rahla/camel:/deploy
      - ./rahla/data:/data
      - ./rahla/code:/code
      - ./settings.xml:/rahla/etc/settings.xml
  
  minio:
    container_name: minio
    hostname: minio
    image:  minio/minio:RELEASE.2023-06-19T19-52-50Z
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001
    environment:
    - MINIO_ACCESS_KEY=minioadmin
    - MINIO_SECRET_KEY=minioadmin
    volumes:
    - ./minio/data:/data